uonafya/cpims-2.3beta

cpovc_forms/views.py
templates/forms/new_wellbeing.html

* add event_id CPAR
* add redirect to ovc_view after caseplan submit

* fix date-time conversion

---

cpims/settings.py
cpims/settings_LOCAL_28360.py
cpovc_forms/forms.py
static/js/cpara-validate-benchmark.js
templates/forms/new_cpara.html

cpara qn 1.2 validation

---

cpovc_registry/views.py
templates/registry/person_new.html

* Fix issue with duplication of caregiver
* Fix issue with labeling of new caregiver as 'CCGV'
* Fix issue attaching caregiver to new child

fix attaching / duplicating caregiver to child

---

cpims/settings.py
cpovc_reports/queries.py
templates/reports/pivot_datim_mer.html
templates/reports/pivot_datim_mer23.html

datim mer23 mer22

---

cpovc_reports/queries.py

registration list, mer23 pepfar summary, list served

registration list, mer23 pepfar summary, list served

---

templates/forms/case_plan_template.html

removing first_cpara + date check qns

removing first_cpara + date check qns

---

templates/forms/new_cpara.html

removing duplicated qn 16.4 & 16.5

removing duplicated qn 16.4 & 16.5

---

static/js/wellbeing-skipto.js
static/js/wellbeing.js

wellbeing validation & skipto polishing

wellbeing validation & skipto polishing

---

cpovc_reports/queries.py

* Datim mer 22
* Serverd two quaters

report updates

---

cpovc_registry/functions.py

Fix get chvs functions
Cascades to 
- CHV search
- CHV addition
- Check if CBO has CHV 
etc

fix get_chvs

---

docs/pull_request_template.md

- The template improves the quality of pull requests made to ease review and ensure the developer has gone through a list of checklist items
- Some [context here](https://docs.microsoft.com/en-us/azure/devops/repos/git/pull-request-templates?view=azure-devops) on pull request review templates

Add pull request review template

---

cpovc_forms/forms.py
cpovc_forms/urls.py
cpovc_forms/views.py
templates/forms/new_hivmanagementform.html
templates/ovc/view_child.html

Implemented HIV Management Form (HTML Views, and Form Logic)

Ft hiv management form

---

.gitignore
templates/forms/case_plan_template.html

refining display of past caseplan template

refining display of past caseplan template

---

cpovc_forms/forms.py
cpovc_forms/models.py
cpovc_forms/views.py
static/js/cpt-script.js
templates/forms/case_plan_template.html

30 day limit on updating caseplan template

30 day limit on updating caseplan template

---

templates/forms/case_plan_template.html

refining past caseplan templare records view

refining past caseplan templare records view

---

cpovc_forms/views.py
templates/forms/new_hivscreeningtool.html

Added a function to allow easy disabling (& possibly skipping) of questions & applied this to Q1 which has an age condition

conditional display of Q1 depending on age

---

cpovc_ovc/forms.py
templates/ovc/home.html

[IssueTracker #157](https://mohissuetracker.uonbi.ac.ke/issues/157)
- [x ] Functional Testing
- [x ] End-To-End Testing
- [ x] I have performed a self-review of my own code
- [ x] My changes generate no new warnings

Ft fillforms

---

cpovc_registry/views.py
templates/registry/view_person.html

showing ovcs of a caregiver in registry/person/view profile

showing ovcs of a caregiver in registry/person/view profile

---

cpovc_forms/views.py

editing caseplan update days limit

editing caseplan update days limit

---

cpovc_ovc/functions.py

editing (adding & removing options) in ovc eligibility

editing (adding & removing options) in ovc eligibility

---

cpovc_registry/functions.py
cpovc_registry/views.py

On editing of OVC, adding caregiver is added to household
https://mohissuetracker.uonbi.ac.ke/issues/83

adding of caregivers to household on ovc edit page

---

cpovc_forms/views.py
templates/forms/new_case_plan_monitoring.html

Add previous cpara monitoring cases

---

templates/forms/new_hivscreeningtool.html

skip logic as per the physical tool

skip logic

---

cpovc_ovc/views.py

Fix issue when viewing or editing ovc and ovc has no caretaker, it keeps redirecting without fail 
https://mohissuetracker.uonbi.ac.ke/issues/84

Fix cyclic redundancy error when caregiver is null

---

cpovc_forms/forms.py
cpovc_forms/models.py
cpovc_forms/views.py
templates/forms/new_case_plan_monitoring.html
templates/forms/new_hivscreeningtool.html

UI changes in hiv risk screening tool

hiv screening modification

---

cpovc_reports/functions.py

fixed column f that was showing domain codes instead of full descriptions

 translating domain to full description

---

requirements.txt

Security fixes - Pillow and djangorestframework

fixed outdated libraries-pillow and drf

---

requirements.txt

https://mohissuetracker.uonbi.ac.ke/issues/181
Reverted to DRF-version-3.3.3

Fix library update

---

requirements.txt

revert drf-3.3.3

---

cpovc_forms/forms.py
cpovc_forms/views.py
templates/forms/new_hivmanagementform.html

-removed preload form data feature on ovc hiv management form.
-added length validation form some form fields
-added cpims event object to hiv management on save action.

remove preloaded data feature

---

.coveragerc
.travis.yml
README.md
cpims/test_settings.py
cpovc_main/tests.py
cpovc_main/tests/test_models.py
cpovc_registry/functions.py
requirements/base.txt
requirements/dev.txt

Sample Tests for the Codebase
Through running `$ python manage.py test --settings=cpims.test_settings`

Add a sample test and update README.

---

cpims/logging_config.py
cpims/settings.py
requirements/base.txt

- Ensure console logger is properly configured
- Setup sentry logging for prod environment
[Ticket Link](https://mohissuetracker.uonbi.ac.ke/issues/185)
- 1. Example logs sent to sentry 
- 2. Example alerting send to mails from sentry (this can always be deactivated)
- 3. Example console logging

Configure logging and log aggregation

---

cpovc_forms/views.py

fixed MultiValueDictKeyError

---

templates/ovc/edit_child.html

Hiding the viral load button if the HIV status isn't +ve

ovc_edit_hiv_viral_load_btn_hide

---

templates/registry/person_new.html

`When changing from
https://mohissuetracker.uonbi.ac.ke/issues/187

fix change date validation when change from child to caregiver

---

cpovc_registry/functions.py

Fix sibling search

---

templates/forms/case_plan_template.html
templates/forms/form1a_events.html
templates/forms/new_cpara.html
templates/forms/new_dreamsform.html
templates/forms/new_form1b.html
templates/forms/new_hhva.html
templates/forms/new_wellbeing.html
templates/forms/new_wellbeingadolescent.html
templates/ovc/household.html
templates/ovc/view_child.html

zoom display fixes

---

cpovc_forms/forms.py
cpovc_forms/views.py

give save form feedback

---

templates/forms/new_hivscreeningtool.html
templates/registry/person_new.html

Hiv screening skip logic

---

cpovc_forms/tests/test_hiv_screening_tool_views.py
cpovc_forms/views.py

Do a POST test for the new hiv screening tool
https://mohissuetracker.uonbi.ac.ke/issues/184

New hivscreeningtool post test

---

cpovc_forms/forms.py
cpovc_forms/views.py
templates/forms/new_hivmanagementform.html

implement 
ART therapy, where the response is 'no', the date should not be a requirement 
requirement.
issue: https://mohissuetracker.uonbi.ac.ke/issues/189

Hiv managemnt

---

cpovc_forms/views.py
static/js/cpara-skipto.js
templates/forms/new_form1b.html

checked skip logic in CPARA form. Most works well. Only issue in benchmark assignment has been fixed though.
Form 1B month validation fixed too (JS end)

skip logic in CPARA form & Form 1B month validation

---

cpovc_forms/migrations/0021_auto_20190712_1506.py
cpovc_forms/migrations/0022_auto_20190712_1904.py

migrations for renaming ovchivmanagement model attributes

---

templates/forms/new_cpara.html
templates/menus.html

modified cpara qs2.3 and added docs-link

---

cpovc_forms/forms.py
cpovc_forms/views.py
templates/forms/new_cpara.html

fixed cpara form tab navigation

fixed cpara form tab navigation

---

cpovc_forms/forms.py

Reverts uonafya/cpims-2.3beta#138
Undo the changes on cpovc_forms/forms.py, line 111. Change **'Please select'** to **False**

Revert "F1a fix"

---

static/js/cpt-script.js

caseplan form & update:: enforcing validation

caseplan_events enforcing validation

---

README.md

https://mohissuetracker.uonbi.ac.ke/issues/192
Docker setup readme

added docker setup instructions -readme

---

cpovc_forms/forms.py
templates/forms/new_hivmanagementform.html

Hiv mngmnt

---

README.md
docker/django/start

https://mohissuetracker.uonbi.ac.ke/issues/192

updated readme and docker startup commands

---

cpovc_forms/views.py
templates/forms/new_cpara.html

Past cpara listing

---

cpims/settings.py
static/js/cpara-skipto.js
templates/forms/new_cpara.html

added skip check qn before qn 13.3

added skip check qn before qn 13.3

---

templates/registry/view_person.html

Show ovcs of caregiver

---

cpovc_ovc/functions.py

https://mohissuetracker.uonbi.ac.ke/issues/219

Fixed household duplication while attaching caregiver to OVC

---

cpovc_ovc/functions.py

https://mohissuetracker.uonbi.ac.ke/issues/219

fix on update caregiver

---

cpovc_registry/views.py
templates/registry/person_edit.html
templates/registry/person_new.html

*Fix issue with location for ward not clearing data after county change
*Fix issue for county info to pre-poplulate on edit
https://mohissuetracker.uonbi.ac.ke/issues/220

Fix location dropdown for edit and registration

---

static/css/style.css
templates/forms/new_hivscreeningtool.html

hiv screening tool validations done again (changes mysteriously undone)

hiv screening tool validations done again (changes mysteriously undone)

---

static/js/cpt-script.js
templates/forms/case_plan_template.html
templates/forms/update_cpt.html

improvements to validation of caseplan & caseplan update forms

Caseplan validation

---

templates/registry/person_edit.html
templates/registry/person_new.html

Add ward validation to person registry and person edit
https://mohissuetracker.uonbi.ac.ke/issues/223

 fix ward validaiton for registry

---

cpovc_forms/functions.py

fix form1b saving:
pointing form1b fields values from **item_description_short** to **item_id**

fix form1b saving

---

cpovc_offline_mode/helpers.py
cpovc_offline_mode/views.py
static/js/offline_mode/service.js
static/js/offline_mode/templates_events.js
templates/base.html

Reverts uonafya/cpims-2.3beta#159
[Ticket ](https://mohissuetracker.uonbi.ac.ke/issues/224)
There is some duplication of form tabs and menus when user is online

Revert "Hide ovc care offline menu if user is online (#159)"

---

cpovc_forms/migrations/0023_auto_20190719_1216.py

Cpims scripts

---

cpovc_main/functions.py

Fix the search for child based on Org unit. (Person registry)

Fix the search based on Org unit

---

templates/forms/new_wellbeingadolescent.html

validation rules on well being adolesent

Navigation fixes

---

static/js/cpt-script.js

caseplan submission fix

---

static/css/style.css
static/js/wellbeing-skipto.js
templates/forms/new_wellbeing.html

style fixes & validation improvements

Wellbeing validation

---

cpovc_forms/migrations/0024_auto_20190722_0827.py

fix migrations

---

cpovc_forms/views.py

fix caregiver

---

cpovc_forms/forms.py
templates/forms/new_wellbeing.html

forms fixes for wellbeing

---

cpovc_forms/views.py

fix wellbieing type

---

cpovc_ovc/forms.py
templates/forms/new_hivscreeningtool.html
templates/ovc/view_child.html

[Rename label-HIV Screening Tool to HIV Risk Assessment](https://mohissuetracker.uonbi.ac.ke/issues/230)
[label-HIV Screening Tool to HIV Risk Assessment](https://mohissuetracker.uonbi.ac.ke/issues/230) 

Renamed label to HIV Risk Assessment

---

.gitignore

Restore report folder to cpims. 

restore reports folder

---

templates/forms/form1a_events.html
templates/forms/new_form1b.html
templates/ovc/view_child.html

renaming labels

---

cpovc_reports/functions.py

Removing print commands on translation of column f (domain) in cpara report (17)

removing prints

---

cpovc_forms/views.py

changed the days update limit in OVC forms to 90 days

updated all edit days limit to 90 days

---

static/js/cpara-validate-benchmark.js

Updated/new function to score benchmark in CPARA, to be tested

cpara new skip logic

---

cpovc_forms/views.py

past form1b is_void=False

---

cpovc_ovc/functions.py

valid schools in ovc edit education

valid schools in ovc edit education

---

data_cleanup/models.py
data_cleanup/sql/case_plan.sql
data_cleanup/urls.py
data_cleanup/views.py
templates/data_cleanup/filter.html

`Case Plan Data Quality`
[Link to ticket](https://mohissuetracker.uonbi.ac.ke/issues/249)

Add case plan models and filters

---

cpovc_forms/tests/test_hiv_screening_tool_views.py

syntax fix

---

cpovc_forms/views.py

removed date_delinked from sibling fetches in forms

removed date_delinked from sibling fetches in forms

---

cpovc_forms/views.py

cpara sibling listing

---

cpovc_forms/views.py

Sibling listing in forms

---

cpovc_forms/models.py
cpovc_forms/sql/fix_monitoring_id_seq.sql

Fix ovc_monitoring_id throwing null when saving
https://mohissuetracker.uonbi.ac.ke/issues/251

Fix ovc monitoring

---

templates/forms/edit_form1a.html
templates/forms/form1a_events.html

form1a UI fixes

---

cpovc_forms/models.py

fix cpara monitoring uuid field

---

cpovc_main/fixtures/case_plan_fixtures.csv.json

add case plan fixure

---

templates/ovc/view_child.html

renamed hiv risk assessment to hiv risk screening

renamed hiv risk assessment to hiv risk screening

---

templates/ovc/edit_child.html

fix Refresh error in viral load save

Viral load refresh error

---

cpovc_ovc/views.py

Reverts uonafya/cpims-2.3beta#246

Revert "fix issue with failing assigning of cbo id for incomplete child in ch…"

---

cpovc_forms/models.py
cpovc_ovc/models.py
templates/ovc/view_child.html

* Fix date timezone warnings for OVCHIVRiskScreening 
* Clean ovc view
* Clean model

Fix ovc hiv risk screening date timezone warnings

---

data_cleanup/models.py
data_cleanup/sql/case_plan.sql
data_cleanup/sql/form1b_quality.sql
data_cleanup/sql/ovc_care_services_quality.sql
data_cleanup/sql/priority_quality.sql
data_cleanup/views.py
templates/data_cleanup/filter.html
templates/menus.html

`Add exit date to the filters`
[Add DQA exit date](https://mohissuetracker.uonbi.ac.ke/issues/256)

DQA add exit date

---

cpims/settings.py
templates/ovc/view_child.html

link fix in ovc_view

---

data_cleanup/models.py
data_cleanup/sql/ovc_care_services_quality.sql
data_cleanup/templatetags/choice_fields_filter.py
data_cleanup/tests/test_templatetags.py
data_cleanup/views.py
templates/data_cleanup/filter.html

`Filter Services by date from and date to`
[Link to ticket](https://mohissuetracker.uonbi.ac.ke/issues/257)

DQA services date filter

---

cpovc_forms/views.py
templates/forms/new_cpara.html
templates/ovc/view_child.html

view siblings in cpara

---

cpovc_forms/forms.py
cpovc_forms/views.py
cpovc_ovc/views.py
templates/forms/new_hivmanagementform.html
templates/ovc/view_child.html

Remove required fields

---

cpovc_reports/queries.py

screening report

---

cpovc_forms/views.py

Modified save in caseplan

---

cpovc_reports/queries.py

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] Test A
- [ X] I have performed a self-review of my own code
- [ X] My changes generate no new warnings

not served update

---

templates/base.html

added gtag script

---

cpovc_forms/admin.py

Add admin page for OVC care question for question management

Add admin page for ovc care questions

---

cpovc_forms/views.py
templates/forms/new_wellbeing.html

form stracture

---

cpovc_forms/admin.py
cpovc_reports/parameters.py
cpovc_reports/queries.py
cpovc_reports/urls.py
cpovc_reports/views.py
templates/menus.html

Datim mer24

---

.gitignore
cpims/settings.py
static/css/style.css
templates/base.html
templates/dashboard.html
templates/forms/alternative_family_care.html
templates/forms/background_details.html
templates/forms/case_record_sheet.html
templates/forms/csi.html
templates/forms/forms_index.html
templates/forms/forms_registry.html
templates/forms/residential_placement.html
templates/locked.html
templates/login.html
templates/menus.html
templates/ovc/home.html
templates/ovc/register_child.html
templates/ovc/view_child.html
templates/registration/password_reset.html
templates/registration/password_reset_confirm.html
templates/registration/password_reset_done.html
templates/registry/delete_person.html
templates/registry/index.html
templates/registry/org_units_index.html
templates/registry/person_search.html
templates/registry/persons_search.html
templates/reports/cluster.html
templates/settings/data.html
templates/settings/reports.html
templates/terms.html

Several UI improvements: typography, colors, layout etc. This is WIP

Ui improvements

---

cpovc_reports/queries.py

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [X ] Test A
- [X ] I have performed a self-review of my own code
- [ X] My changes generate no new warnings

form1A summary update

---

static/css/style.css
templates/forms/form1a_events.html

form1a layout fixes

---

cpims/settings.py
cpims/urls.py
cpovc_forms/migrations/0025_auto_20200316_0817.py
cpovc_forms/migrations/0026_auto_20200316_0847.py
templates/menus.html
templates/simple_forums/base.html
templates/simple_forums/search.html
templates/simple_forums/thread_create.html
templates/simple_forums/thread_detail.html
templates/simple_forums/thread_list.html

[django-simple-forums](https://django-simple-forums.readthedocs.io)
```
$ pip install django-simple-forums
$ python manage.py migrate simple_forums
```

simple forum implementation

---

cpims/settings.py

set kmhfl configs

---

cpims/settings.py
cpovc_ovc/management/commands/update_viralload.py
crontab.txt
utilities/update_ovc_viralload.py

Creates a cron job to enable automatic updates of OVC viral loads as per the NASCOP API.

Update ovc viral load

---

cpovc_forms/fixtures/dreams_initial.json
initial_jsons.bat
initial_jsons.sh

Add dreams form fixures to cpims

setup dreams fixures

---

cpims/settings.py

add nascop credentials to settings

---

cpovc_forms/forms.py
cpovc_forms/views.py
templates/forms/edit_dreams.html
templates/forms/new_dreamsformupdated.html

Dreamsedits

---

static/js/cpara-skipto.js
static/js/cpara-validate-benchmark.js
static/js/cpt-script.js
templates/forms/new_cpara.html
templates/forms/update_cpt.html
templates/ovc/view_child.html

skip qn 16

---

cpovc_main/models.py

`add new field to class ListAnswers to match with DCS codebase`

add answer_code field to ListAnswers

---

cpovc_ovc/forms.py
cpovc_ovc/functions.py

* add search by ID for OVC
